name: test tag
on:
  push:
    branches:
      - main
jobs:
  test-tag:
    runs-on: ubuntu-latest
    steps:
      - name: version
        run: |
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
