name: test tag
on:
  push:
    tags:
      - v**
jobs:
  test-tag:
    runs-on: ubuntu-latest
    steps:
      - name: version
        run: |
          export VERSION=$(basename $GITHUB_REF)
          echo $VERSION
          echo $GITHUB_REF_NAME
